### ISSUE TITLE
Feature Request: Implement rarity-skin

### ISSUE THREAD

**Issue by t0bou** [Rarity-Extended/RarityExtended#100]
### What problem will this solve ? ✅
Each class gets one appearance, but there is no way to personalize your look, reducing the feeling of ownership of one's summoners.

<br />  

### What is your solution 🔧
I suggest to integrate the rarity-skin open standard, managed by this contract : https://ftmscan.com/address/0xd1447fe5e70d58204946d61224643738ba54f5cc#code 
It allows players to choose any NFT and assign them as avatars for their summoner. When no skin is assigned to a summoner, the current, default appearance is displayed. When the RaritySkinManager contract signals that a NFT is assigned to a summoner, the relevant image is fetched using ERC721's tokenURI() method.

<br />  

### Additional context 📝
I'm the developer of this standard, if you signal that you are interested, I offer to develop the solution and submit it to you through merge request.

**Comment by Major-Eth** [comment]
Thank you for this PR !
I like this standard and I would be nice to have this to Rarity Extended !
We currently have a lot of things going on but if you submit a PR for this I would be pleased to review that !

Feel free to pm me on telegram if you have some questions : @major-eth
