### ISSUE TITLE
Feature Request: add The Rarity Forest (req's level 5)

### ISSUE THREAD

**Issue by Ceazor** [Rarity-Extended/RarityExtended#13]
### What problem will this solve ? ✅
add more adventures, 
<br />  

### What is your solution 🔧
add it to the tavern.. 

SPECS
4-7Day locking, to find treasure
Treasure is relative to character level (I think)
Req, level 5 to enter

we could have.

_There is a dark looking man sitting at a table in the corner. His face is hidden under a full faced mask. 
<br />  
Do you want to approach him?_

{add a CHARISMA filter here?}

_He speaks of a Dark Forest to the North about a week's travel, there and back, with danger but treasure. He is willing to guide you there, but was hurt too much to enter the forest with you. He doesn't want anything in return for helping you, just that you vanquish the beast that has crippled him.
<br />  
Do you accept his offer?_
<br />  
We can use this beast.
![image](https://user-images.githubusercontent.com/73511897/132787880-67d29058-e17f-4429-8f1b-7319f4ef46b8.png)

since Major bought this pack already.
https://elthen.itch.io/monster-sprite-pack
<br />  
<br />  

### Additional context 📝
I found this 
https://ftmscan.com/address/0xb37d3d79ea86B0334d9322c695339D577A3D57be#writeContract

It seems to be a vault like contract for characters that has some cool features.  This will need some auditing/testing to see if it's not a rug.. 

https://github.com/TheAustrian1998/theRarityForest/blob/master/contracts/theRarityForest.sol#L86
That's the creator if anyone know him. 

it would be nice to implement some community content.

**Comment by TheAustrian1998** [comment]
Hey, thanks for include RarityForest!

Some clarifications:
- To enter the forest you need level 2 (I lowered requirement cause was to hard to achieve level 5).
- Treasure is determined in days of research, example: research 4 days, you receive [item A, item B, item C], research 5 days, you receive [item B, item D, item E]. Is a little tricky and random, but i can explain it all.
- Some items repeat, others are more scarce.
- To `startResearch` you need to be the owner or approved of the summoner. So, you can keep doing adventures while you are in the forest. (Contract never hold your summoner).

I love the story you wrote to introduce the forest!

**Comment by TBouder** [comment]
I am working on that right now!
I think we may need some adjustment on the story : it's a two part story, you first need to send you adventurer, and then you need to dig up the treasure after 4/7 days. There is no monster to fight for this adventure :(

IMO, what we can do would be to keep a very similar story, without the monster, and for the UI, you can send you adventurer do the quest, and once it can dig the tresure, you would have a popup to "Take your treasure and go back home"

**Comment by TBouder** [comment]
PR for this in review!
