### ISSUE TITLE
Make characters according to spec

### ISSUE THREAD

**Issue by saltyfacu** [Rarity-Extended/RarityExtended#17]
Right now we are using preliminary characters. We need to adapt the current ones using this spec: https://hackmd.io/Fc6J7u65QPyhfm4XW9x4Ig?view

**Comment by Ceazor** [comment]
I clean these up tomorrow and try to figure out a way i can make EPS. 

When you get a chance add the source clips.

**Comment by Major-Eth** [comment]
@saltyfacu @Ceazor 
With the new Monk and the new Barbarian, what is the next class to upgrade?

**Comment by saltyfacu** [comment]
Bard ;)
