### ISSUE TITLE
Feature Request: Removed Failed Characters from able to go on quest

### ISSUE THREAD

**Issue by Ceazor** [Rarity-Extended/RarityExtended#25]
### What problem will this solve ? ✅
WHen I send a character down into the cellar to fight a rat, but he finds nothing, he remains as an option to go down again. 
Same issue when he gets KO'd (this is not so much of an issue, as they can level up, deploy stat points, and try agian)

on
https://rarityextended.com/tavern?tab=the-cellar

<br />  

### What is your solution 🔧
I don't know.. there will need to be info stored,, seemingly.
<br />  

### Additional context 📝
**Add any other context or screenshots about the feature request here.**

**Comment by TBouder** [comment]
Right now, if we don't want to use a DB, the best solution (imo) would be to display a `(!)` for example (warning) if the scout result would be 0 for an adventurer. This is not great, but that's the less prone to error.
