### ISSUE TITLE
Bug: MetaMask - RPC Error: Internal JSON-RPC error. 

### ISSUE THREAD

**Issue by ykou** [Rarity-Extended/RarityExtended#41]
### What happened 🆘

If my account already has a summoner, then I create another summoner, it triggers an error: `execution reverted: ERC721: approved query for nonexistent token`. 

![image](https://user-images.githubusercontent.com/5376112/133188470-37585198-7051-448e-9699-120e5918f8b4.png)

### To Reproduce 🔂
Steps to reproduce the behavior: create a new summoner from the tavern. 

### More 🔎
- Browser : 
- FTM Provider : 
- Adventurer ID :

**Comment by TBouder** [comment]
Hey !
Thank you for this issue
I could not reproduce that, but this is weird you get this. This is from a [public function on the ERC721 standard from OZ](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.3.0/contracts/token/ERC721/ERC721.sol#L126). Could you counter you were on Fantom network and give me the RPC you used (and the RarityExtended URL if possible) ?

Thank you 🙏

**Comment by ykou** [comment]
Here's my Fantom Opera network details: 

![image](https://user-images.githubusercontent.com/5376112/133365908-ae468a77-3e40-41a1-bf71-1a1b426a0292.png)

The URL is https://rarityextended.com/

**Comment by DarkGhost7** [comment]
I am also seeing this error on mine quite a bit too. 
![image](https://user-images.githubusercontent.com/38810205/133974360-58383344-31fe-469c-af17-d60c1086867b.png)

**Comment by DarkGhost7** [comment]
my rpc 
![image](https://user-images.githubusercontent.com/38810205/133974439-f6ad7810-6b4b-4869-a3ed-605fb529bb14.png)

**Comment by DarkGhost7** [comment]
For more details about the error 
![image](https://user-images.githubusercontent.com/38810205/133974897-bb0ba023-fa58-4321-990b-1b740bb0169f.png)

**Comment by Major-Eth** [comment]
I close for now.
For the record, the issue was the RPC on the user's side.
A solid RPC for Fantom is `https://rpc.ftm.tools`.

We will work on workaround to suggest RPC
