### ISSUE TITLE
Improvement: change gold claiming text

### ISSUE THREAD

**Issue by saltyfacu** [Rarity-Extended/RarityExtended#45]
### What problem will this solve ? ✅
Text for claiming gold is: `WOULD YOU LIKE TO CLAIM YOUR 1000 GOLDS ?`

<br />  

### What is your solution 🔧
Change it to this: `WOULD YOU LIKE TO CLAIM YOUR GOLD (1000 COINS)?`

<br />

**Comment by Ceazor** [comment]
How about this..

Ye have bounty to claim. (1000 COINS) Would you like it now?
