### ISSUE TITLE
Feature Request: Add Quest source to Job Board

### ISSUE THREAD

**Issue by Ceazor** [Rarity-Extended/RarityExtended#47]
### What problem will this solve ? ✅
WHen you talk to Lara and chose a quest.. let's add in people there. 
<br />  

### What is your solution 🔧
Add a pic of quest giver and a speech bubble. In this case its Facu. (put him on the X in the image) If so we need to change the text to 1st person.. so this instead 

"I BE FACU, THE TAVERN’S OWNER, ME HEARD SOME SCURRYING ABOUT DOWN IN DA CELLAR. I WENT DOWN TO CHECK IT AND FOUND SWARMS OF HUNGRY RATS. IN ME EARLIER DAYS, **FACU THE COMMITTER** WOULD HAVE SQUASHED THOSE PESTS, BUT THESE DAYS I BE WEAK AND FRAIL. "

DO YOU WANT TO HELP HIM OUT? ANYTHING YOU FIND YOU GET TO KEEP.

<br />  

### Additional context 📝
![image](https://user-images.githubusercontent.com/73511897/133566398-c71ff28c-b2bb-4559-bf6c-19c6822a2060.png)

**Comment by Major-Eth** [comment]
I close this, we will work on some design Improvements :)
