### ISSUE TITLE
Feature Request: Change notification location

### ISSUE THREAD

**Issue by kennedybaird** [Rarity-Extended/RarityExtended#66]
### What problem will this solve ? ✅
Notifications stack unreasonably over the content when doing multiple actions.

Would suggest them being in the bottom left, as Metamask pops up in top right.
![notifications](https://user-images.githubusercontent.com/20593811/134328821-d8785e64-1434-4a48-84d1-aa91e26b9fdb.png)

**Comment by Major-Eth** [comment]
Hi !
Thank you for this !
We are working on a workaround !
