### ISSUE TITLE
Bug: Multiple failed contract interactions when restoring forest items

### ISSUE THREAD

**Issue by kennedybaird** [Rarity-Extended/RarityExtended#67]
### What happened 🆘
Here are a couple of the trans ids:

0xbd8f5e852419f7b8a53b47c02600c723b5dedc53d9b433a35148294adfd16444
0xbaee4121675514f171b4c58d8f2da297e203736521cb976655d4f111e6073688

2 others worked so I'm not sure what is going on.

### More 🔎
- Browser : Chrome
- FTM Provider : Metamask
- Adventurer ID :

**Comment by Major-Eth** [comment]
Hey !
Thank you for reporting this, we will investigate !
@TheAustrian1998, any idea on that ?

**Comment by TheAustrian1998** [comment]
Hey @kennedybaird! thanks for reporting. It's very weird because all parameters are normal. One thing that all tx have in common is that used 100% of gas. Maybe a gas estimation error in frontend. We will look for a workaround.
