### ISSUE TITLE
Bug: Where to look at the cost of earn ftm

### ISSUE THREAD

**Issue by MuHongWeiWei** [Rarity-Extended/RarityExtended#68]
### What happened 🆘
**A clear and concise description of what the bug is.**

### More 🔎
- Browser : 
- FTM Provider : 
- Adventurer ID :

**Comment by saltyfacu** [comment]
What do you mean by cost? There's no cost

**Comment by MuHongWeiWei** [comment]
Here is a pledge, where to look at the cost or how to recover it
![](https://i.imgur.com/57zmOKi.png)

**Comment by MuHongWeiWei** [comment]
Understand that the development of this feature is in progress, I wish the development smoothly

**Comment by Major-Eth** [comment]
Hey !
Yes, you can check the [Preview](https://rarity-git-feature-bank-rarityextended.vercel.app/town/bank) if you wish !
It's not approved yet, maybe some bug, but it's maybe what you want :)

Tell us if there is something else that could help !
Thank you !

**Comment by Ceazor** [comment]
It seems to me that he is expecting some cost to withdraw.. like a fee or something.

Withdrawals will only cost gas.
