### ISSUE TITLE
Bug: CSS selector is not correct when npthing were selected at first

### ISSUE THREAD

**Issue by pandadefi** [Rarity-Extended/RarityExtended#70]
### What happened 🆘
This is already the light mode

<img width="223" alt="Screen Shot 2021-09-22 at 5 04 10 PM" src="https://user-images.githubusercontent.com/87183122/134369663-b77482a8-1806-459d-8617-25f28b1c4b7f.png">

Once clicked it will sitch to dark and the message is correct

### To Reproduce 🔂

Open https://rarityextended.com/ on private mode.

### More 🔎
- Browser : Firefox
- FTM Provider : 
- Adventurer ID :

**Comment by Major-Eth** [comment]
Thank you ! 
Fixed in the PR #69
